// Project Topic: Usernames
// This project, to satify the requirements, will output a randomly generated username
// using a list of words generated by ChatGPT

const nameStrings = [
  'Flamingo',
  'Galactic',
  'Rainbow',
  'Phoenix',
  'Mystic',
  'Electric',
  'Sparkle',
  'Dragon',
  'Pixel',
  'Neon',
  'Thunder',
  'Ninja',
  'Shadow',
  'Cosmic',
  'Unicorn',
  'Stardust',
  'Samurai',
  'Firefly',
  'Supernova',
  'Cyber',
  'Dreamer',
  'Velocity',
  'Glitch',
  'Enigma',
  'Infinity',
  'Midnight',
  'Mystic',
  'Serenity',
  'Vortex',
  'Tempest',
  'Titan',
  'Omega',
  'Nova',
  'Quantum',
  'Nexus',
  'Eclipse',
  'Hyperion',
  'Voyager',
  'Astral',
  'Arcane',
];

// Random Idx Helper
const generateRandomIdx = arrLength => Math.floor(Math.random() * (arrLength - 1));

// Random Name String Helper
const pickRandomName = arr => arr[generateRandomIdx(arr.length)];

// Generate Username
const generateUsername = arr => {
  let user1 = pickRandomName(arr);
  let user2 = pickRandomName(arr);

  while (user1 === user2) {
    user2 = pickRandomName(arr);
  }

  return `Random Username: ${user1} ${user2}`;
};

console.log(generateUsername(nameStrings));
